name: Protobuf

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Set up environment
        run: ./env-proto.sh

      - name: Lint
        run: make proto/lint

      - name: Generate
        run: make proto/generate && git diff --exit-code
